In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Function to read the .txt files into a DataFrame

In [2]:

df_list = []
file_locs = ['../scraped_data/data.txt','../scraped_data/cardekho.txt']
for file in file_locs:
    with open(file, 'r', encoding='utf-8') as rf:
        for line in rf:
            inp = eval(line)
            main_dict = {}

            for key, value in inp.items():
                if(key == 'info'):
                    for keyinfo,valueinfo in inp[key].items():
                        main_dict[keyinfo] = valueinfo   
                else:
                        main_dict[key] = value
            
            if (file == '../scraped_data/data.txt'):
              main_dict['Source'] = 'Cars24'   
            else:
                main_dict['Source'] = 'CarDekho'

            df_list.append(main_dict)

df = pd.DataFrame(df_list)

The data for this project has been scraped from both Cars24 and CarDekho. Both have been stored in two seperate .txt files, 'data.txt' and 'cardekho.txt', in different ways. Each line of the .txt file is a python dictionary that stores relevant information about the car. The above function reads in each line, converts it to a dictionary, and appends it to a list of dictionaries. This list is then converted into a dataframe df.

# Basic Overview of the Data

In [3]:
df.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type,Source
0,2020 Jeep Compass LONGITUDE PLUS 1.4 PETROL AT,₹8.50 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Jul 2020,Petrol,"116,562 km",Automatic,1368cc,1st,Feb 2020,No,******8927,Nov 2026,3rd Party,Cars24
1,2016 Mahindra XUV500 W6 AT 1.99,₹4.51 lakh,FAIR PRICE according to our Price Indicator.,DL-10,Aug 2016,Diesel,"238,933 km",Automatic,1997cc,1st,Jun 2016,No,******6357,NaN,NaN,Cars24
2,2012 Hyundai Eon D-LITE,₹0.84 lakh,STEAL DEAL according to our Price Indicator.,UP-15,Jan 2013,CNG,"94,507 km",Manual,814cc,2nd,Jan 2012,No,******2716,Nov 2026,3rd Party,Cars24
3,2013 Hyundai i20 SPORTZ 1.2,₹1.81 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Mar 2013,CNG,"120,121 km",Manual,1197cc,2nd,Feb 2013,No,******7982,Dec 2026,3rd Party,Cars24
4,2014 Honda City 1.5L I-VTEC SV,₹3.07 lakh,STEAL DEAL according to our Price Indicator.,DL-4C,May 2014,Petrol,"77,884 km",Manual,1497cc,2nd,Apr 2014,No,******9657,NaN,NaN,Cars24

In [4]:
print(f"There are {df.shape[0]} rows and {df.shape[1]} columns in the dataset.")

There are 16832 rows and 16 columns in the dataset.

In [5]:
print(f"There are {df.duplicated().value_counts().iloc[1]} duplicated rows.")

There are 2904 duplicated rows.

Since the data has been scraped over multiple days, the same listings get captured by the scraper. Additionally, CarDekho also lists some cars found on Cars24, which could be contributing to the number of duplicates.

# Modifying Datatypes :

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16832 entries, 0 to 16831
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   model            16832 non-null  object
 1   price            16832 non-null  object
 2   price_score      16532 non-null  object
 3   plate            16832 non-null  object
 4   Reg. year        16832 non-null  object
 5   Fuel             16832 non-null  object
 6   KM driven        16832 non-null  object
 7   Transmission     16832 non-null  object
 8   Engine capacity  16516 non-null  object
 9   Ownership        16832 non-null  object
 10  Make year        16832 non-null  object
 11  Spare key        9886 non-null   object
 12  Reg number       9886 non-null   object
 13  Insurance        4521 non-null   object
 14  Insurance type   11467 non-null  object
 15  Source           16832 non-null  object
dtypes: object(16)
memory usage: 2.1+ MB

Almost all rows are of an incorrect datatype. THis is to be rectified. Many rows are also null, some having so few values that using them for any meaningful analysis is almost impossible. They are to be dropped. 

Certain information given by Cars24 about cars is not present in CarDekho. For example, `Spare key` and `Reg number` are not provided on CarDekho, which explains their equal number of missing values. 

Insurance and Insurance type have inconsistent number of nulls, even though they are related to each other. One reason for this is the CarDekho-v/s-Cars24 missing data mentioned in the previous line.

In [7]:
# creating a copy:
data = df.copy()

In [8]:
# Modifying Ownership :
maps = {'1st':1, '2nd':2, '3rd':3, '4th':4, '5th': 5, '6th':6, '7th':7, 
        'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner':4, 'Fifth Owner':5}
data['Ownership'] = data['Ownership'].replace(maps)

C:\Users\sisfi\AppData\Local\Temp\ipykernel_3968\2707634852.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Ownership'] = data['Ownership'].replace(maps)

In [9]:
# function to parse car model column :
import re
def parse_model(x):

    x = x.upper()

    if(x.find('\n') != -1):  # cardekho cars
        temp_split = x.split('\n')
        model = temp_split[0].split(' ')
        variant = temp_split[1]

        if(model[0].isdigit() and len(model[0]) == 4):  # parsing the model name
            model = model[1:]
        else:
            model = model[0:]
        
        if(model[1] == 'SUZUKI'):
            del model[1]

        garbages = ['PETROL','CNG','DIESEL', 'AT', 'MT', 'AMT']   # removing fuel description from variant
        for garbage in garbages:
            if(garbage in variant):
                variant = variant.replace(garbage,'')
        
        variant = re.sub(r'\d\.\d[L]?', '', variant)    

        model = ' '.join(model).strip()
        
    else:  # cars24 cars
        if('NEW' in x):
            x = x.replace('NEW','')

        temp_split = x.split(' ')
        for i in range(len(temp_split) - 1):  # cleaning up extra ''s
            if(temp_split[i] == ''):
                del temp_split[i]

        if(temp_split[2] == 'GRAND' or temp_split[2] == 'WAGON'):
            model = temp_split[1]+" "+temp_split[2]+' '+temp_split[3]
            variant = ' '.join(temp_split[4:])
        else:
            model = temp_split[1]+' '+temp_split[2]
            variant = ' '.join(temp_split[3:]).strip()
        
        garbages = ['PETROL','CNG','DIESEL', ' AT', ' MT', ' AMT', ' I-VTEC']   # removing fuel description from variant
        for garbage in garbages:
            if(garbage in variant):
                variant = variant.replace(garbage,'')
        
        variant = re.sub(r'\d\.\d[L]?', '', variant)   
    return(model,variant)

In [10]:
# trimming model column :
data[['model','variant']] = data['model'].apply(lambda x: pd.Series(parse_model(x)))
data['model'].value_counts()[:10]

model
HONDA CITY           847
HYUNDAI CRETA        831
MARUTI WAGON R       673
MARUTI SWIFT         657
MARUTI BALENO        595
KIA SELTOS           572
HYUNDAI GRAND I10    548
HONDA AMAZE          496
TATA NEXON           451
HYUNDAI I10          415
Name: count, dtype: int64

In [11]:
data.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type,Source,variant
0,JEEP COMPASS,₹8.50 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Jul 2020,Petrol,"116,562 km",Automatic,1368cc,1,Feb 2020,No,******8927,Nov 2026,3rd Party,Cars24,LONGITUDE PLUS
1,MAHINDRA XUV500,₹4.51 lakh,FAIR PRICE according to our Price Indicator.,DL-10,Aug 2016,Diesel,"238,933 km",Automatic,1997cc,1,Jun 2016,No,******6357,NaN,NaN,Cars24,W6 9
2,HYUNDAI EON,₹0.84 lakh,STEAL DEAL according to our Price Indicator.,UP-15,Jan 2013,CNG,"94,507 km",Manual,814cc,2,Jan 2012,No,******2716,Nov 2026,3rd Party,Cars24,D-LITE
3,HYUNDAI I20,₹1.81 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Mar 2013,CNG,"120,121 km",Manual,1197cc,2,Feb 2013,No,******7982,Dec 2026,3rd Party,Cars24,SPORTZ
4,HONDA CITY,₹3.07 lakh,STEAL DEAL according to our Price Indicator.,DL-4C,May 2014,Petrol,"77,884 km",Manual,1497cc,2,Apr 2014,No,******9657,NaN,NaN,Cars24,SV

The original `model` column of the car included a lot of redundant information such as the year, fuel-type, etc. that already have dedicated columns for it. Hence, these components are dropped. Readability has also improved.

One problem that arose here is that Maruti Swift and Maruti Suzuki Swift were being errenuosly considered to be separate vehicles despite the fact that they are the same. This edge case is also handled.

In [12]:
data.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type,Source,variant
0,JEEP COMPASS,₹8.50 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Jul 2020,Petrol,"116,562 km",Automatic,1368cc,1,Feb 2020,No,******8927,Nov 2026,3rd Party,Cars24,LONGITUDE PLUS
1,MAHINDRA XUV500,₹4.51 lakh,FAIR PRICE according to our Price Indicator.,DL-10,Aug 2016,Diesel,"238,933 km",Automatic,1997cc,1,Jun 2016,No,******6357,NaN,NaN,Cars24,W6 9
2,HYUNDAI EON,₹0.84 lakh,STEAL DEAL according to our Price Indicator.,UP-15,Jan 2013,CNG,"94,507 km",Manual,814cc,2,Jan 2012,No,******2716,Nov 2026,3rd Party,Cars24,D-LITE
3,HYUNDAI I20,₹1.81 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Mar 2013,CNG,"120,121 km",Manual,1197cc,2,Feb 2013,No,******7982,Dec 2026,3rd Party,Cars24,SPORTZ
4,HONDA CITY,₹3.07 lakh,STEAL DEAL according to our Price Indicator.,DL-4C,May 2014,Petrol,"77,884 km",Manual,1497cc,2,Apr 2014,No,******9657,NaN,NaN,Cars24,SV

In [13]:
# replacing price column :
def price_conversion(x):
    x = x.lower().replace('₹','')

    if(x.endswith('lakh')):
        x = x.replace('lakh','')
        x = float(x)*100000

    elif(x.endswith('crore')):
        x = x.replace('crore', '')
        x = float(x)*10000000
    elif(x.endswith('thousand')):
        x = x.replace('thousand','')
        x = float(x)*1000
    
    return(x)

data['price'] = data['price'].map(price_conversion)

In [14]:
# converting KM driven and engine capacity column:
data['KM driven'] = data['KM driven'].str.replace(r'[A-Za-z,\s]+', '', regex=True).astype('int')
data['Engine capacity'] = data['Engine capacity'].str.strip().str.replace('cc','').astype('Float64')

In [15]:
# trimming price_score column :
data['price_score'] = data['price_score'].replace('NA', np.nan)
data.loc[data['price_score'].notna(), 'price_score'] = data.loc[data['price_score'].notna(), 'price_score'].str.split(' ').map(lambda x: x[0]+' '+x[1])

This change only keeps the basic price evaluation label of the Cars24 listing, improving readability.

In [16]:
# converting Reg. year and Make year
data['Reg. year'] = pd.to_datetime(data['Reg. year']).dt.year
data['Make year'] = pd.to_datetime(data['Make year']).dt.year

C:\Users\sisfi\AppData\Local\Temp\ipykernel_3968\4109392050.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Reg. year'] = pd.to_datetime(data['Reg. year']).dt.year
C:\Users\sisfi\AppData\Local\Temp\ipykernel_3968\4109392050.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Make year'] = pd.to_datetime(data['Make year']).dt.year

The Year columns, previously stored as objects have been converted to datetime objects.

# Examining Nulls :

In [17]:
df.isna().sum()

model                  0
price                  0
price_score          300
plate                  0
Reg. year              0
Fuel                   0
KM driven              0
Transmission           0
Engine capacity      316
Ownership              0
Make year              0
Spare key           6946
Reg number          6946
Insurance          12311
Insurance type      5365
Source                 0
dtype: int64

- `Spare Key` and `Reg Number` both have same number of null values, because they have been sourced from CarDekho, which does not provide this info.
- `price_score` field will have more nulls than depicted, because this info is not given in the CarDekho records either.
- `Engine capacity` nulls can be interpolated from other cars of the same model.
- `Insurance type` has less number of nulls than `Insurance`, because CarDekho data doesn't provide data for the 'Insurance' column.

In [18]:
# Replacing Insurance type nulls w/ unknown:
data.loc[data['Insurance type'].isna(),'Insurance type'] = 'Unknown'
data['Insurance type'] = data['Insurance type'].replace('-','Unknown')

data['Insurance type'] = data['Insurance type'].replace('Zero Dep', 'Zero Depreciation')
data['Insurance type'] = data['Insurance type'].replace('3rd Party', 'Third Party')

data.loc[data['Insurance type'].str.startswith('Plans from'),'Insurance type'] = 'Info Given'

In [19]:
data['Insurance type'].value_counts()

Insurance type
Unknown              7985
Third Party          4148
Comprehensive        3342
Info Given            927
Zero Depreciation     430
Name: count, dtype: int64

`Insurance type` is a meaningful attribute of a vehicle. If a seller does not provide Insurance information while selling their car, it might be a red flag. A relatively new car of a top-tier model not having insurance information is curious, and it might be a genuine signal that can be picked up by an ML model. Hence, instead of dropping the whole column altogether, the nulls have been replaced with `Unknown`.

In [20]:
# Replacing Engine capacity with other cars of the same make :
data['Engine capacity'] = data['Engine capacity'].fillna(
    data.groupby(['model', 'variant'])['Engine capacity'].transform('mean'))

In [21]:
data[data['Engine capacity'].isna()]

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type,Source,variant
269,SKODA SUPERB,1000000.0,HIGH PRICE,DL-11,2016,Petrol,29669,Automatic,<NA>,1,2016,Yes,******6924,NaN,Unknown,Cars24,STYLE TSI
478,TATA NEXON,1050000.0,STEAL DEAL,DL-9E,2024,Electric,39505,Automatic,<NA>,2,2023,Yes,*****3581,NaN,Unknown,Cars24,EV EMPOWERED LONG RANGE
572,TATA NEXON,1150000.0,HIGH PRICE,DL-7G,2022,Electric,50868,Automatic,<NA>,1,2022,Yes,*****7722,NaN,Unknown,Cars24,EV XZ PLUS LUX
648,TATA PUNCH,1100000.0,GREAT PRICE,RJ-02,2024,Electric,55278,Automatic,<NA>,2,2024,Yes,******4895,NaN,Unknown,Cars24,EV EMPOWERED PLUS S LONG RANGE
782,TATA NEXON,1154000.0,HIGH PRICE,DL-9C,2025,Petrol,13351,Automatic,<NA>,1,2025,Yes,******5871,Jul 2028,Third Party,Cars24,PURE PLUS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9208,TATA NEXON,1084000.0,HIGH PRICE,BR-01,2024,Petrol,28632,Automatic,<NA>,1,2024,Yes,BR01******,Jul 2027,Third Party,Cars24,CREATIVE PLUS REVOTRON 6 DT
9324,MG ZS,1550000.0,FAIR PRICE,DL-10,2023,Electric,58099,Automatic,<NA>,1,2023,No,DL10******,Apr 2027,Third Party,Cars24,EV EXCITE
9696,HYUNDAI CRETA,1840000.0,FAIR PRICE,HR-26,2025,Petrol,8541,Automatic,<NA>,1,2025,Yes,HR26******,Jun 2028,Third Party,Cars24,CRETA SX (O) MPI IVT
9826,TATA NEXON,940000.0,GREAT PRICE,HR-98,2024,Petrol,33043,Automatic,<NA>,1,2023,Yes,HR98*****,Dec 2026,Zero Depreciation,Cars24,XZA PLUS LUX SUNROOF KAZIRANGA
9862,KIA SELTOS,1201000.0,NaN,HR-30,2025,Petrol,5525,Manual,<NA>,1,2025,No,HR30**8746,Nov 2028,Third Party,Cars24,HTE (O)

In [22]:
# for cars where model + variant are too limiting :

data['Engine capacity'] = data['Engine capacity'].fillna(
    data.groupby('model')['Engine capacity'].transform('median')
)

In [23]:
data[data['Engine capacity'].isna()]

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type,Source,variant
963,MG ZS,1623000.0,GREAT PRICE,DL-13,2025,Electric,18403,Automatic,<NA>,1,2024,No,******8399,Feb 2028,Third Party,Cars24,EV EXCITE PRO
2034,MG ZS,1650000.0,HIGH PRICE,DL-9E,2024,Electric,49930,Automatic,<NA>,1,2024,Yes,*****4683,Apr 2027,Third Party,Cars24,EV EXECUTIVE
2793,CITROEN E,807000.0,FAIR PRICE,DL-9E,2023,Electric,48639,Automatic,<NA>,1,2023,Yes,*****1395,NaN,Unknown,Cars24,C3 FEEL
2898,MG COMET,622000.0,STEAL DEAL,DL-9E,2024,Electric,19780,Automatic,<NA>,1,2024,Yes,*****5547,Jul 2027,Third Party,Cars24,EXCITE FC
2900,MG ZS,1435000.0,STEAL DEAL,DL-8E,2024,Electric,35917,Automatic,<NA>,1,2024,No,*****1779,Jul 2027,Third Party,Cars24,EV EXCITE PRO
3691,MG ZS,1200000.0,STEAL DEAL,DL-7G,2022,Electric,86273,Automatic,<NA>,1,2022,No,*****0672,NaN,Unknown,Cars24,EV EXCLUSIVE
6881,MG ZS,1200000.0,STEAL DEAL,DL-7G,2022,Electric,86273,Automatic,<NA>,1,2022,No,*****0672,NaN,Unknown,Cars24,EV EXCLUSIVE
8547,MAHINDRA XUV400,1620000.0,FAIR PRICE,DL-6E,2025,Electric,11869,Automatic,<NA>,1,2025,Yes,DL6E*****,NaN,Unknown,Cars24,EL PRO 3 KWH
9324,MG ZS,1550000.0,FAIR PRICE,DL-10,2023,Electric,58099,Automatic,<NA>,1,2023,No,DL10******,Apr 2027,Third Party,Cars24,EV EXCITE

In [24]:
data.loc[data['Engine capacity'].isna(),'Engine capacity'] = 0

- Cars belonging to the same variant-model combination are almost certain to have the same engine capacities. Hence, they have been interpolated. 

- The above imputation method still left some nulls. These vehicles where simply imputed with the median engine capacity for their specific model. This is likely to be less accurate. 

- Cars that still had null values were EVs, which do not have engine capacities in the first place. They were replaced with 0.

# Dropping Unnecessary Rows and Columns :

In [26]:
data.drop_duplicates(inplace=True, keep='first')

In [27]:
dup = data.drop(['price_score', 'Source'], axis = 1)
dup_indices = dup[dup.duplicated() == True].index 
data.drop(index=dup_indices, inplace=True)

In [28]:
print(f"After dropping duplicates, {data.shape[0]} rows remain.")

After dropping duplicates, 13748 rows remain.

Some duplicates have crept into the data since scraping has been done over multiple days, with the script capturing the same listings over and over again. Moreover, CarDekho also provides some listings that have been sourced from Cars24. Since we have separately scraped Cars24 ourselves, these listings have been previously captured by us and so they have been dropped too.

In [29]:
del data['Reg number']
del data['Spare key']
del data['Insurance']